name: vts_kit_flutter_onboarding_demo
description: VTS Flutter Onboarding Demo

publish_to: 'none'
version: 0.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  vts_kit_flutter_onboarding:
    path: ../lib/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/image.png
    - images/image.png
    - images/anh1.png
    - images/anh2.png
    - images/anh3.png
